# Generated by Django 2.0.6 on 2018-07-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('R_E_M', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='alt_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
