# Generated by Django 2.0.6 on 2018-08-24 21:53

import R_E_M.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('R_E_M', '0002_moviestillphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteScreenShot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(blank=True, max_length=50, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=R_E_M.models.website_screen_shot_image_uh)),
                ('alt_text', models.CharField(blank=True, max_length=50, null=True)),
                ('date_taken', models.CharField(max_length=50)),
                ('image_details', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_photos', to=settings.AUTH_USER_MODEL)),
                ('website_screenshots', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_screenshots', to='R_E_M.Website')),
            ],
        ),
        migrations.AlterField(
            model_name='moviestillphoto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=R_E_M.models.movie_still_photo_image_uh),
        ),
    ]
