# Generated by Django 2.0.6 on 2018-09-27 01:45

import R_E_M.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('R_E_M', '0003_auto_20180914_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_cover',
            field=models.ImageField(blank=True, null=True, upload_to=R_E_M.models.album_cover_image_uh),
        ),
    ]
