# Generated by Django 2.0.6 on 2018-09-29 15:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('R_E_M', '0005_auto_20180929_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_date_built',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
