# Generated by Django 2.0.6 on 2018-09-01 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('R_E_M', '0005_auto_20180901_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='website',
            old_name='website_screenshot',
            new_name='main_page',
        ),
        migrations.RemoveField(
            model_name='websitescreenshot',
            name='date_taken',
        ),
        migrations.RemoveField(
            model_name='websitescreenshot',
            name='image_details',
        ),
    ]
