# Generated by Django 2.0.6 on 2018-09-02 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('R_E_M', '0006_auto_20180901_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='image_details',
        ),
    ]
